main: fr.discowzombie.advancedwhitelist.spigot.AdvancedWhitelistSpigot
name: AdvancedWhitelist
author: DiscowZombie
version: 1.0-SNAPSHOT
api-version: 1.13
commands:
  advancedwhitelist:
    aliases:
      - awl
    description: ""